### ISSUE TITLE
Hungry team

### ISSUE THREAD

**Issue by DjoykeAbyah** [elenavoronin/webserve#7]
You know who you are... the question is why

![youknowwho](https://github.com/user-attachments/assets/7759f311-2a88-43f5-8d98-402a03abeced)

**Comment by elenavoronin** [comment]
we are cats and we get all the shnackies

**Comment by elenavoronin** [comment]
![output_480](https://github.com/user-attachments/assets/cf465ccf-1ce6-4acd-8cee-32380f077840)

**Comment by elenavoronin** [comment]
we solved the problem and got the shackiez
